\RequirePackage[l2tabu, orthodox]{nag}

\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{tikz}[2016/02/05 Minimal Latex Class]

\LoadClass{standalone}

\usepackage{tikz}
\usetikzlibrary{arrows}
\usetikzlibrary{automata}
\usetikzlibrary{backgrounds}
\usetikzlibrary{calc}
\usetikzlibrary{calendar}
\usetikzlibrary{er}
\usetikzlibrary{intersections}
\usetikzlibrary{mindmap}
\usetikzlibrary{matrix}
\usetikzlibrary{patterns}
\usetikzlibrary{shapes}
\usetikzlibrary{snakes}
\usetikzlibrary{topaths}
\usetikzlibrary{trees}
